services:
  payload:
    image: santic-revamp-cms:${IMAGE_TAG:-latest}
    ports:
      - '3000:3000'

    env_file:
      - .env.uat

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'