server:
  http_listen_port: 9080  # 管理端口（可访问 /metrics 查看状态）
  grpc_listen_port: 0     # 禁用GRPC（非必需）

positions:
  filename: /var/log/positions.yaml  # 关键！记录文件读取位置

clients:
  - url: http://loki:3100/loki/api/v1/push  # Loki接收地址
    batchwait: 1s          # 批量发送等待时间
    batchsize: 102400       # 每批最大字节数(100KB)

scrape_configs:
- job_name: odoo_logs
  static_configs:
  - targets: [localhost]   # 标识数据来源节点（非功能参数）
    labels:
      job: odoo17          # 主标签（Grafana按此筛选）
      env: prod            # 环境标签
      app: erp             # 应用类型
      __path__: /var/log/odoo/*.log  # 关键！监控路径（支持通配符）
  pipeline_stages:         # 日志处理管道（增强功能）
    - match:
        selector: '{job="odoo17"}'
        stages:
        - regex: 
            expression: '.*(?P<level>WARNING|ERROR|CRITICAL).*'  # 提取日志级别
        - labels:
            level:  # 将提取的level转为标签