# 全局配置
global:
# 设置数据采集频率为2分钟1次。默认1分钟1次。可以设置scrape_configs中覆盖。
  scrape_interval: 2m
# 评估告警规则的间隔，默认为1分钟。一般和scrape_interval设置相同的值。
  evaluation_interval: 2m
# 每次抓取数据的超时时间，默认为10秒 
  scrape_timeout: 10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "server_node"
    static_configs:
      - targets: ["172.16.160.18:9100"]
        labels:
          role: "kanban"
      - targets: ["172.16.160.10:9100"]
        labels:
          role: "gitlab"
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 30s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
       # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"